# Generated by Django 5.2.2 on 2025-09-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_customuser_last_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_check'),
        ),
    ]
